import 'package:flutter_application_5/Elements/models_element.dart';


var elementsChimiques = [
  ElementChimique(
    nom: 'Hydrogène',
    symbole: 'H',
    numeroAtomique: '1',
    masseAtomique: '1.008',
    groupe: 'Non-métaux',
    periode: '1',
    configurationElectronique: '1s1',
    pointDeFusion: '-259.16',
    pointDebullition: '-252.87',
    decouverte: '1766',
    histoire: "Découvert par Henry Cavendish en 1766.",
  ),
 
  ElementChimique(
    nom: 'Hélium',
    symbole: 'He',
    numeroAtomique: '2',
    masseAtomique: '4.0026',
    groupe: 'Gaz nobles',
    periode: '1',
    configurationElectronique: '1s2',
    pointDeFusion: '-272.20',
    pointDebullition: '-268.93',
    decouverte: '1868',
    histoire: "Découvert dans le spectre solaire en 1868.",
  ),
  ElementChimique(
    nom: 'Lithium',
    symbole: 'Li',
    numeroAtomique: '3',
    masseAtomique: '6.94',
    groupe: 'Métaux alcalins',
    periode: '2',
    configurationElectronique: '[He] 2s1',
    pointDeFusion: '180.54',
    pointDebullition: '1342',
    decouverte: '1817',
    histoire: "Découvert par Johan August Arfvedson en 1817.",
  ),
  ElementChimique(
    nom: 'Béryllium',
    symbole: 'Be',
    numeroAtomique: '4',
    masseAtomique: '9.0122',
    groupe: 'Métaux alcalino-terreux',
    periode: '2',
    configurationElectronique: '[He] 2s2',
    pointDeFusion: '1287',
    pointDebullition: '2469',
    decouverte: '1797',
    histoire: "Découvert par Louis-Nicolas Vauquelin en 1797.",
  ),
  ElementChimique(
    nom: 'Bore',
    symbole: 'B',
    numeroAtomique: '5',
    masseAtomique: '10.81',
    groupe: 'Métalloïdes',
    periode: '2',
    configurationElectronique: '[He] 2s2 2p1',
    pointDeFusion: '2076',
    pointDebullition: '3927',
    decouverte: '1808',
    histoire: "Découvert par Joseph Louis Gay-Lussac et Louis Jacques Thénard en 1808.",
  ),
  ElementChimique(
    nom: 'Carbone',
    symbole: 'C',
    numeroAtomique: '6',
    masseAtomique: '12.011',
    groupe: 'Non-métaux',
    periode: '2',
    configurationElectronique: '[He] 2s2 2p2',
    pointDeFusion: '3550',
    pointDebullition: '4827',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Azote',
    symbole: 'N',
    numeroAtomique: '7',
    masseAtomique: '14.007',
    groupe: 'Non-métaux',
    periode: '2',
    configurationElectronique: '[He] 2s2 2p3',
    pointDeFusion: '-210.0',
    pointDebullition: '-195.79',
    decouverte: '1772',
    histoire: "Découvert par Daniel Rutherford en 1772.",
  ),
  ElementChimique(
    nom: 'Oxygène',
    symbole: 'O',
    numeroAtomique: '8',
    masseAtomique: '15.999',
    groupe: 'Non-métaux',
    periode: '2',
    configurationElectronique: '[He] 2s2 2p4',
    pointDeFusion: '-218.79',
    pointDebullition: '-182.95',
    decouverte: '1774',
    histoire: "Découvert par Carl Wilhelm Scheele et Joseph Priestley en 1774.",
  ),
  ElementChimique(
    nom: 'Fluor',
    symbole: 'F',
    numeroAtomique: '9',
    masseAtomique: '18.998',
    groupe: 'Halogènes',
    periode: '2',
    configurationElectronique: '[He] 2s2 2p5',
    pointDeFusion: '-219.67',
    pointDebullition: '-188.12',
    decouverte: '1886',
    histoire: "Isolé par Henri Moissan en 1886.",
  ),
  ElementChimique(
    nom: 'Néon',
    symbole: 'Ne',
    numeroAtomique: '10',
    masseAtomique: '20.180',
    groupe: 'Gaz nobles',
    periode: '2',
    configurationElectronique: '[He] 2s2 2p6',
    pointDeFusion: '-248.59',
    pointDebullition: '-246.08',
    decouverte: '1898',
    histoire: "Découvert par Sir William Ramsay et Morris Travers en 1898.",
  ),
  ElementChimique(
    nom: 'Sodium',
    symbole: 'Na',
    numeroAtomique: '11',
    masseAtomique: '22.990',
    groupe: 'Métaux alcalins',
    periode: '3',
    configurationElectronique: '[Ne] 3s1',
    pointDeFusion: '97.72',
    pointDebullition: '883',
    decouverte: '1807',
    histoire: "Isolé par Sir Humphry Davy en 1807.",
  ),
  ElementChimique(
    nom: 'Magnésium',
    symbole: 'Mg',
    numeroAtomique: '12',
    masseAtomique: '24.305',
    groupe: 'Métaux alcalino-terreux',
    periode: '3',
    configurationElectronique: '[Ne] 3s2',
    pointDeFusion: '650',
    pointDebullition: '1091',
    decouverte: '1755',
    histoire: "Découvert par Joseph Black en 1755.",
  ),
  ElementChimique(
    nom: 'Aluminium',
    symbole: 'Al',
    numeroAtomique: '13',
    masseAtomique: '26.982',
    groupe: 'Métaux pauvres',
    periode: '3',
    configurationElectronique: '[Ne] 3s2 3p1',
    pointDeFusion: '660.32',
    pointDebullition: '2519',
    decouverte: '1825',
    histoire: "Isolé par Hans Christian Ørsted en 1825.",
  ),
  ElementChimique(
    nom: 'Silicium',
    symbole: 'Si',
    numeroAtomique: '14',
    masseAtomique: '28.085',
    groupe: 'Métalloïdes',
    periode: '3',
    configurationElectronique: '[Ne] 3s2 3p2',
    pointDeFusion: '1414',
    pointDebullition: '2900',
    decouverte: '1824',
    histoire: "Isolé par Jöns Jacob Berzelius en 1824.",
  ),
  ElementChimique(
    nom: 'Phosphore',
    symbole: 'P',
    numeroAtomique: '15',
    masseAtomique: '30.974',
    groupe: 'Non-métaux',
    periode: '3',
    configurationElectronique: '[Ne] 3s2 3p3',
    pointDeFusion: '44.15',
    pointDebullition: '280.5',
    decouverte: '1669',
    histoire: "Découvert par Hennig Brand en 1669.",
  ),
  ElementChimique(
    nom: 'Soufre',
    symbole: 'S',
    numeroAtomique: '16',
    masseAtomique: '32.06',
    groupe: 'Non-métaux',
    periode: '3',
    configurationElectronique: '[Ne] 3s2 3p4',
    pointDeFusion: '115.21',
    pointDebullition: '444.6',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Chlore',
    symbole: 'Cl',
    numeroAtomique: '17',
    masseAtomique: '35.45',
    groupe: 'Halogènes',
    periode: '3',
    configurationElectronique: '[Ne] 3s2 3p5',
    pointDeFusion: '-101.5',
    pointDebullition: '-34.04',
    decouverte: '1774',
    histoire: "Isolé par Carl Wilhelm Scheele en 1774.",
  ),
  ElementChimique(
    nom: 'Argon',
    symbole: 'Ar',
    numeroAtomique: '18',
    masseAtomique: '39.948',
    groupe: 'Gaz nobles',
    periode: '3',
    configurationElectronique: '[Ne] 3s2 3p6',
    pointDeFusion: '-189.34',
    pointDebullition: '-185.85',
    decouverte: '1894',
    histoire: "Découvert par Lord Rayleigh et Sir William Ramsay en 1894.",
  ),
  ElementChimique(
    nom: 'Potassium',
    symbole: 'K',
    numeroAtomique: '19',
    masseAtomique: '39.098',
    groupe: 'Métaux alcalins',
    periode: '4',
    configurationElectronique: '[Ar] 4s1',
    pointDeFusion: '63.5',
    pointDebullition: '759',
    decouverte: '1807',
    histoire: "Isolé par Sir Humphry Davy en 1807.",
  ),
  ElementChimique(
    nom: 'Calcium',
    symbole: 'Ca',
    numeroAtomique: '20',
    masseAtomique: '40.078',
    groupe: 'Métaux alcalino-terreux',
    periode: '4',
    configurationElectronique: '[Ar] 4s2',
    pointDeFusion: '842',
    pointDebullition: '1484',
    decouverte: '1808',
    histoire: "Isolé par Sir Humphry Davy en 1808.",
  ),
  ElementChimique(
    nom: 'Scandium',
    symbole: 'Sc',
    numeroAtomique: '21',
    masseAtomique: '44.956',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d1 4s2',
    pointDeFusion: '1541',
    pointDebullition: '2836',
    decouverte: '1879',
    histoire: "Découvert par Lars Fredrik Nilson en 1879.",
  ),
  ElementChimique(
    nom: 'Titane',
    symbole: 'Ti',
    numeroAtomique: '22',
    masseAtomique: '47.867',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d2 4s2',
    pointDeFusion: '1668',
    pointDebullition: '3287',
    decouverte: '1791',
    histoire: "Découvert par William Gregor en 1791.",
  ),
  ElementChimique(
    nom: 'Vanadium',
    symbole: 'V',
    numeroAtomique: '23',
    masseAtomique: '50.942',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d3 4s2',
    pointDeFusion: '1910',
    pointDebullition: '3407',
    decouverte: '1801',
    histoire: "Découvert par Andrés Manuel del Río en 1801.",
  ),
  ElementChimique(
    nom: 'Chrome',
    symbole: 'Cr',
    numeroAtomique: '24',
    masseAtomique: '51.996',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d5 4s1',
    pointDeFusion: '1907',
    pointDebullition: '2671',
    decouverte: '1797',
    histoire: "Découvert par Louis-Nicolas Vauquelin en 1797.",
  ),
  ElementChimique(
    nom: 'Manganèse',
    symbole: 'Mn',
    numeroAtomique: '25',
    masseAtomique: '54.938',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d5 4s2',
    pointDeFusion: '1246',
    pointDebullition: '2061',
    decouverte: '1774',
    histoire: "Isolé par Johan Gottlieb Gahn en 1774.",
  ),
  ElementChimique(
    nom: 'Fer',
    symbole: 'Fe',
    numeroAtomique: '26',
    masseAtomique: '55.845',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d6 4s2',
    pointDeFusion: '1538',
    pointDebullition: '2862',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Cobalt',
    symbole: 'Co',
    numeroAtomique: '27',
    masseAtomique: '58.933',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d7 4s2',
    pointDeFusion: '1495',
    pointDebullition: '2927',
    decouverte: '1735',
    histoire: "Découvert par Georg Brandt en 1735.",
  ),
  ElementChimique(
    nom: 'Nickel',
    symbole: 'Ni',
    numeroAtomique: '28',
    masseAtomique: '58.693',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d8 4s2',
    pointDeFusion: '1455',
    pointDebullition: '2730',
    decouverte: '1751',
    histoire: "Découvert par Axel Fredrik Cronstedt en 1751.",
  ),
  ElementChimique(
    nom: 'Cuivre',
    symbole: 'Cu',
    numeroAtomique: '29',
    masseAtomique: '63.546',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d10 4s1',
    pointDeFusion: '1084.62',
    pointDebullition: '2562',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Zinc',
    symbole: 'Zn',
    numeroAtomique: '30',
    masseAtomique: '65.38',
    groupe: 'Métaux de transition',
    periode: '4',
    configurationElectronique: '[Ar] 3d10 4s2',
    pointDeFusion: '419.53',
    pointDebullition: '907',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Gallium',
    symbole: 'Ga',
    numeroAtomique: '31',
    masseAtomique: '69.723',
    groupe: 'Métaux pauvres',
    periode: '4',
    configurationElectronique: '[Ar] 3d10 4s2 4p1',
    pointDeFusion: '29.76',
    pointDebullition: '2204',
    decouverte: '1875',
    histoire: "Découvert par Paul-Émile Lecoq de Boisbaudran en 1875.",
  ),
  ElementChimique(
    nom: 'Germanium',
    symbole: 'Ge',
    numeroAtomique: '32',
    masseAtomique: '72.63',
    groupe: 'Métalloïdes',
    periode: '4',
    configurationElectronique: '[Ar] 3d10 4s2 4p2',
    pointDeFusion: '938.25',
    pointDebullition: '2833',
    decouverte: '1886',
    histoire: "Découvert par Clemens Winkler en 1886.",
  ),
  ElementChimique(
    nom: 'Arsenic',
    symbole: 'As',
    numeroAtomique: '33',
    masseAtomique: '74.922',
    groupe: 'Métalloïdes',
    periode: '4',
    configurationElectronique: '[Ar] 3d10 4s2 4p3',
    pointDeFusion: '817',
    pointDebullition: '614',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Sélénium',
    symbole: 'Se',
    numeroAtomique: '34',
    masseAtomique: '78.971',
    groupe: 'Non-métaux',
    periode: '4',
    configurationElectronique: '[Ar] 3d10 4s2 4p4',
    pointDeFusion: '221',
    pointDebullition: '685',
    decouverte: '1817',
    histoire: "Découvert par Jöns Jacob Berzelius en 1817.",
  ),
  ElementChimique(
    nom: 'Brome',
    symbole: 'Br',
    numeroAtomique: '35',
    masseAtomique: '79.904',
    groupe: 'Halogènes',
    periode: '4',
    configurationElectronique: '[Ar] 3d10 4s2 4p5',
    pointDeFusion: '-7.2',
    pointDebullition: '58.8',
    decouverte: '1826',
    histoire: "Découvert par Antoine Jérôme Balard en 1826.",
  ),
  ElementChimique(
    nom: 'Krypton',
    symbole: 'Kr',
    numeroAtomique: '36',
    masseAtomique: '83.798',
    groupe: 'Gaz nobles',
    periode: '4',
    configurationElectronique: '[Ar] 3d10 4s2 4p6',
    pointDeFusion: '-157.36',
    pointDebullition: '-153.22',
    decouverte: '1898',
    histoire: "Découvert par Sir William Ramsay et Morris Travers en 1898.",
  ),
  ElementChimique(
    nom: 'Rubidium',
    symbole: 'Rb',
    numeroAtomique: '37',
    masseAtomique: '85.468',
    groupe: 'Métaux alcalins',
    periode: '5',
    configurationElectronique: '[Kr] 5s1',
    pointDeFusion: '39.31',
    pointDebullition: '688',
    decouverte: '1861',
    histoire: "Découvert par Robert Bunsen et Gustav Kirchhoff en 1861.",
  ),
  ElementChimique(
    nom: 'Strontium',
    symbole: 'Sr',
    numeroAtomique: '38',
    masseAtomique: '87.62',
    groupe: 'Métaux alcalino-terreux',
    periode: '5',
    configurationElectronique: '[Kr] 5s2',
    pointDeFusion: '777',
    pointDebullition: '1382',
    decouverte: '1790',
    histoire: "Découvert par Adair Crawford en 1790.",
  ),
  ElementChimique(
    nom: 'Yttrium',
    symbole: 'Y',
    numeroAtomique: '39',
    masseAtomique: '88.906',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d1 5s2',
    pointDeFusion: '1526',
    pointDebullition: '3336',
    decouverte: '1794',
    histoire: "Découvert par Johan Gadolin en 1794.",
  ),
  ElementChimique(
    nom: 'Zirconium',
    symbole: 'Zr',
    numeroAtomique: '40',
    masseAtomique: '91.224',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d2 5s2',
    pointDeFusion: '1855',
    pointDebullition: '4409',
    decouverte: '1789',
    histoire: "Découvert par Martin Heinrich Klaproth en 1789.",
  ),
  ElementChimique(
    nom: 'Niobium',
    symbole: 'Nb',
    numeroAtomique: '41',
    masseAtomique: '92.906',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d4 5s1',
    pointDeFusion: '2477',
    pointDebullition: '4744',
    decouverte: '1801',
    histoire: "Découvert par Charles Hatchett en 1801.",
  ),
  ElementChimique(
    nom: 'Molybdène',
    symbole: 'Mo',
    numeroAtomique: '42',
    masseAtomique: '95.95',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d5 5s1',
    pointDeFusion: '2623',
    pointDebullition: '4639',
    decouverte: '1778',
    histoire: "Découvert par Carl Wilhelm Scheele en 1778.",
  ),
  ElementChimique(
    nom: 'Technétium',
    symbole: 'Tc',
    numeroAtomique: '43',
    masseAtomique: '98',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d5 5s2',
    pointDeFusion: '2157',
    pointDebullition: '4265',
    decouverte: '1937',
    histoire: "Synthétisé par Carlo Perrier et Emilio Segrè en 1937.",
  ),
  ElementChimique(
    nom: 'Ruthénium',
    symbole: 'Ru',
    numeroAtomique: '44',
    masseAtomique: '101.07',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d7 5s1',
    pointDeFusion: '2334',
    pointDebullition: '4150',
    decouverte: '1844',
    histoire: "Découvert par Karl Ernst Claus en 1844.",
  ),
  ElementChimique(
    nom: 'Rhodium',
    symbole: 'Rh',
    numeroAtomique: '45',
    masseAtomique: '102.91',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d8 5s1',
    pointDeFusion: '1964',
    pointDebullition: '3695',
    decouverte: '1803',
    histoire: "Découvert par William Hyde Wollaston en 1803.",
  ),
  ElementChimique(
    nom: 'Palladium',
    symbole: 'Pd',
    numeroAtomique: '46',
    masseAtomique: '106.42',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d10',
    pointDeFusion: '1554.9',
    pointDebullition: '2963',
    decouverte: '1803',
    histoire: "Découvert par William Hyde Wollaston en 1803.",
  ),
  ElementChimique(
    nom: 'Argent',
    symbole: 'Ag',
    numeroAtomique: '47',
    masseAtomique: '107.87',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d10 5s1',
    pointDeFusion: '961.78',
    pointDebullition: '2162',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Cadmium',
    symbole: 'Cd',
    numeroAtomique: '48',
    masseAtomique: '112.41',
    groupe: 'Métaux de transition',
    periode: '5',
    configurationElectronique: '[Kr] 4d10 5s2',
    pointDeFusion: '321.07',
    pointDebullition: '767',
    decouverte: '1817',
    histoire: "Découvert par Friedrich Stromeyer en 1817.",
  ),
  ElementChimique(
    nom: 'Indium',
    symbole: 'In',
    numeroAtomique: '49',
    masseAtomique: '114.82',
    groupe: 'Métaux pauvres',
    periode: '5',
    configurationElectronique: '[Kr] 4d10 5s2 5p1',
    pointDeFusion: '156.6',
    pointDebullition: '2072',
    decouverte: '1863',
    histoire: "Découvert par Ferdinand Reich et Hieronymous Theodor Richter en 1863.",
  ),
  ElementChimique(
    nom: 'Étain',
    symbole: 'Sn',
    numeroAtomique: '50',
    masseAtomique: '118.71',
    groupe: 'Métaux pauvres',
    periode: '5',
    configurationElectronique: '[Kr] 4d10 5s2 5p2',
    pointDeFusion: '231.93',
    pointDebullition: '2602',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Antimoine',
    symbole: 'Sb',
    numeroAtomique: '51',
    masseAtomique: '121.76',
    groupe: 'Métalloïdes',
    periode: '5',
    configurationElectronique: '[Kr] 4d10 5s2 5p3',
    pointDeFusion: '630.63',
    pointDebullition: '1587',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Tellure',
    symbole: 'Te',
    numeroAtomique: '52',
    masseAtomique: '127.60',
    groupe: 'Métalloïdes',
    periode: '5',
    configurationElectronique: '[Kr] 4d10 5s2 5p4',
    pointDeFusion: '449.51',
    pointDebullition: '988',
    decouverte: '1782',
    histoire: "Découvert par Franz-Joseph Müller von Reichenstein en 1782.",
  ),
  ElementChimique(
    nom: 'Iode',
    symbole: 'I',
    numeroAtomique: '53',
    masseAtomique: '126.90',
    groupe: 'Halogènes',
    periode: '5',
    configurationElectronique: '[Kr] 4d10 5s2 5p5',
    pointDeFusion: '113.7',
    pointDebullition: '184.3',
    decouverte: '1811',
    histoire: "Découvert par Bernard Courtois en 1811.",
  ),
  ElementChimique(
    nom: 'Xénon',
    symbole: 'Xe',
    numeroAtomique: '54',
    masseAtomique: '131.29',
    groupe: 'Gaz nobles',
    periode: '5',
    configurationElectronique: '[Kr] 4d10 5s2 5p6',
    pointDeFusion: '-111.9',
    pointDebullition: '-108.1',
    decouverte: '1898',
    histoire: "Découvert par Sir William Ramsay et Morris Travers en 1898.",
  ),
  ElementChimique(
    nom: 'Césium',
    symbole: 'Cs',
    numeroAtomique: '55',
    masseAtomique: '132.91',
    groupe: 'Métaux alcalins',
    periode: '6',
    configurationElectronique: '[Xe] 6s1',
    pointDeFusion: '28.44',
    pointDebullition: '671',
    decouverte: '1860',
    histoire: "Découvert par Robert Bunsen et Gustav Kirchhoff en 1860.",
  ),
  ElementChimique(
    nom: 'Baryum',
    symbole: 'Ba',
    numeroAtomique: '56',
    masseAtomique: '137.33',
    groupe: 'Métaux alcalino-terreux',
    periode: '6',
    configurationElectronique: '[Xe] 6s2',
    pointDeFusion: '727',
    pointDebullition: '1870',
    decouverte: '1808',
    histoire: "Isolé par Sir Humphry Davy en 1808.",
  ),
  ElementChimique(
    nom: 'Lanthane',
    symbole: 'La',
    numeroAtomique: '57',
    masseAtomique: '138.91',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 5d1 6s2',
    pointDeFusion: '920',
    pointDebullition: '3464',
    decouverte: '1839',
    histoire: "Découvert par Carl Gustaf Mosander en 1839.",
  ),
  ElementChimique(
    nom: 'Cérium',
    symbole: 'Ce',
    numeroAtomique: '58',
    masseAtomique: '140.12',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f1 5d1 6s2',
    pointDeFusion: '795',
    pointDebullition: '3443',
    decouverte: '1803',
    histoire: "Découvert par Jöns Jacob Berzelius et Wilhelm Hisinger en 1803.",
  ),
  ElementChimique(
    nom: 'Praséodyme',
    symbole: 'Pr',
    numeroAtomique: '59',
    masseAtomique: '140.91',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f3 6s2',
    pointDeFusion: '931',
    pointDebullition: '3130',
    decouverte: '1885',
    histoire: "Découvert par Carl Auer von Welsbach en 1885.",
  ),
  ElementChimique(
    nom: 'Néodyme',
    symbole: 'Nd',
    numeroAtomique: '60',
    masseAtomique: '144.24',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f4 6s2',
    pointDeFusion: '1021',
    pointDebullition: '3074',
    decouverte: '1885',
    histoire: "Découvert par Carl Auer von Welsbach en 1885.",
  ),
  ElementChimique(
    nom: 'Prométhium',
    symbole: 'Pm',
    numeroAtomique: '61',
    masseAtomique: '145',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f5 6s2',
    pointDeFusion: '1042',
    pointDebullition: '3000',
    decouverte: '1945',
    histoire: "Synthétisé par Jacob A. Marinsky, Lawrence E. Glendenin et Charles D. Coryell en 1945.",
  ),
  ElementChimique(
    nom: 'Samarium',
    symbole: 'Sm',
    numeroAtomique: '62',
    masseAtomique: '150.36',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f6 6s2',
    pointDeFusion: '1072',
    pointDebullition: '1794',
    decouverte: '1879',
    histoire: "Découvert par Paul-Émile Lecoq de Boisbaudran en 1879.",
  ),
  ElementChimique(
    nom: 'Europium',
    symbole: 'Eu',
    numeroAtomique: '63',
    masseAtomique: '151.96',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f7 6s2',
    pointDeFusion: '822',
    pointDebullition: '1529',
    decouverte: '1901',
    histoire: "Découvert par Eugène-Anatole Demarçay en 1901.",
  ),
  ElementChimique(
    nom: 'Gadolinium',
    symbole: 'Gd',
    numeroAtomique: '64',
    masseAtomique: '157.25',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f7 5d1 6s2',
    pointDeFusion: '1312',
    pointDebullition: '3250',
    decouverte: '1880',
    histoire: "Découvert par Jean Charles Galissard de Marignac en 1880.",
  ),
  ElementChimique(
    nom: 'Terbium',
    symbole: 'Tb',
    numeroAtomique: '65',
    masseAtomique: '158.93',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f9 6s2',
    pointDeFusion: '1356',
    pointDebullition: '3230',
    decouverte: '1843',
    histoire: "Découvert par Carl Gustaf Mosander en 1843.",
  ),
  ElementChimique(
    nom: 'Dysprosium',
    symbole: 'Dy',
    numeroAtomique: '66',
    masseAtomique: '162.50',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f10 6s2',
    pointDeFusion: '1412',
    pointDebullition: '2562',
    decouverte: '1886',
    histoire: "Découvert par Paul-Émile Lecoq de Boisbaudran en 1886.",
  ),
  ElementChimique(
    nom: 'Holmium',
    symbole: 'Ho',
    numeroAtomique: '67',
    masseAtomique: '164.93',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f11 6s2',
    pointDeFusion: '1474',
    pointDebullition: '2700',
    decouverte: '1878',
    histoire: "Découvert par Marc Delafontaine et Jacques-Louis Soret en 1878.",
  ),
  ElementChimique(
    nom: 'Erbium',
    symbole: 'Er',
    numeroAtomique: '68',
    masseAtomique: '167.26',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f12 6s2',
    pointDeFusion: '1529',
    pointDebullition: '2868',
    decouverte: '1842',
    histoire: "Découvert par Carl Gustaf Mosander en 1842.",
  ),
  ElementChimique(
    nom: 'Thulium',
    symbole: 'Tm',
    numeroAtomique: '69',
    masseAtomique: '168.93',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f13 6s2',
    pointDeFusion: '1545',
    pointDebullition: '1950',
    decouverte: '1879',
    histoire: "Découvert par Per Teodor Cleve en 1879.",
  ),
  ElementChimique(
    nom: 'Ytterbium',
    symbole: 'Yb',
    numeroAtomique: '70',
    masseAtomique: '173.04',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 6s2',
    pointDeFusion: '824',
    pointDebullition: '1196',
    decouverte: '1878',
    histoire: "Découvert par Jean Charles Galissard de Marignac en 1878.",
  ),
  ElementChimique(
    nom: 'Lutécium',
    symbole: 'Lu',
    numeroAtomique: '71',
    masseAtomique: '174.97',
    groupe: 'Lanthanides',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d1 6s2',
    pointDeFusion: '1663',
    pointDebullition: '3402',
    decouverte: '1907',
    histoire: "Découvert par Carl Auer von Welsbach en 1907.",
  ),
  ElementChimique(
    nom: 'Hafnium',
    symbole: 'Hf',
    numeroAtomique: '72',
    masseAtomique: '178.49',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d2 6s2',
    pointDeFusion: '2233',
    pointDebullition: '4603',
    decouverte: '1923',
    histoire: "Découvert par Dirk Coster et George de Hevesy en 1923.",
  ),
  ElementChimique(
    nom: 'Tantale',
    symbole: 'Ta',
    numeroAtomique: '73',
    masseAtomique: '180.95',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d3 6s2',
    pointDeFusion: '3017',
    pointDebullition: '5458',
    decouverte: '1802',
    histoire: "Découvert par Anders Gustaf Ekeberg en 1802.",
  ),
  ElementChimique(
    nom: 'Tungstène',
    symbole: 'W',
    numeroAtomique: '74',
    masseAtomique: '183.84',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d4 6s2',
    pointDeFusion: '3422',
    pointDebullition: '5930',
    decouverte: '1781',
    histoire: "Découvert par Carl Wilhelm Scheele en 1781.",
  ),
  ElementChimique(
    nom: 'Rhénium',
    symbole: 'Re',
    numeroAtomique: '75',
    masseAtomique: '186.21',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d5 6s2',
    pointDeFusion: '3186',
    pointDebullition: '5596',
    decouverte: '1925',
    histoire: "Découvert par Walter Noddack, Ida Tacke, et Otto Berg en 1925.",
  ),
  ElementChimique(
    nom: 'Osmium',
    symbole: 'Os',
    numeroAtomique: '76',
    masseAtomique: '190.23',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d6 6s2',
    pointDeFusion: '3033',
    pointDebullition: '5012',
    decouverte: '1803',
    histoire: "Découvert par Smithson Tennant en 1803.",
  ),
  ElementChimique(
    nom: 'Iridium',
    symbole: 'Ir',
    numeroAtomique: '77',
    masseAtomique: '192.22',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d7 6s2',
    pointDeFusion: '2446',
    pointDebullition: '4130',
    decouverte: '1803',
    histoire: "Découvert par Smithson Tennant en 1803.",
  ),
  ElementChimique(
    nom: 'Platine',
    symbole: 'Pt',
    numeroAtomique: '78',
    masseAtomique: '195.08',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d9 6s1',
    pointDeFusion: '1768.3',
    pointDebullition: '3825',
    decouverte: '1735',
    histoire: "Connu depuis l'Antiquité, mais redécouvert par Antonio de Ulloa en 1735.",
  ),
  ElementChimique(
    nom: 'Or',
    symbole: 'Au',
    numeroAtomique: '79',
    masseAtomique: '196.97',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d10 6s1',
    pointDeFusion: '1064.18',
    pointDebullition: '2856',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Mercure',
    symbole: 'Hg',
    numeroAtomique: '80',
    masseAtomique: '200.59',
    groupe: 'Métaux de transition',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d10 6s2',
    pointDeFusion: '-38.83',
    pointDebullition: '356.73',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Thallium',
    symbole: 'Tl',
    numeroAtomique: '81',
    masseAtomique: '204.38',
    groupe: 'Métaux pauvres',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d10 6s2 6p1',
    pointDeFusion: '304',
    pointDebullition: '1473',
    decouverte: '1861',
    histoire: "Découvert par Sir William Crookes en 1861.",
  ),
  ElementChimique(
    nom: 'Plomb',
    symbole: 'Pb',
    numeroAtomique: '82',
    masseAtomique: '207.2',
    groupe: 'Métaux pauvres',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d10 6s2 6p2',
    pointDeFusion: '327.46',
    pointDebullition: '1749',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Bismuth',
    symbole: 'Bi',
    numeroAtomique: '83',
    masseAtomique: '208.98',
    groupe: 'Métaux pauvres',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d10 6s2 6p3',
    pointDeFusion: '271.4',
    pointDebullition: '1564',
    decouverte: 'Antiquité',
    histoire: "Connu depuis l'Antiquité.",
  ),
  ElementChimique(
    nom: 'Polonium',
    symbole: 'Po',
    numeroAtomique: '84',
    masseAtomique: '209',
    groupe: 'Métalloïdes',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d10 6s2 6p4',
    pointDeFusion: '254',
    pointDebullition: '962',
    decouverte: '1898',
    histoire: "Découvert par Marie Curie et Pierre Curie en 1898.",
  ),
  ElementChimique(
    nom: 'Astate',
    symbole: 'At',
    numeroAtomique: '85',
    masseAtomique: '210',
    groupe: 'Halogènes',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d10 6s2 6p5',
    pointDeFusion: '302',
    pointDebullition: '337',
    decouverte: '1940',
    histoire: "Synthétisé par Dale R. Corson, Kenneth Ross MacKenzie, et Emilio Segrè en 1940.",
  ),
  ElementChimique(
    nom: 'Radon',
    symbole: 'Rn',
    numeroAtomique: '86',
    masseAtomique: '222',
    groupe: 'Gaz nobles',
    periode: '6',
    configurationElectronique: '[Xe] 4f14 5d10 6s2 6p6',
    pointDeFusion: '-71',
    pointDebullition: '-61.7',
    decouverte: '1899',
    histoire: "Découvert par Friedrich Ernst Dorn en 1899.",
  ),
  ElementChimique(
    nom: 'Francium',
    symbole: 'Fr',
    numeroAtomique: '87',
    masseAtomique: '223',
    groupe: 'Métaux alcalins',
    periode: '7',
    configurationElectronique: '[Rn] 7s1',
    pointDeFusion: '27',
    pointDebullition: '677',
    decouverte: '1939',
    histoire: "Découvert par Marguerite Perey en 1939.",
  ),
  ElementChimique(
    nom: 'Radium',
    symbole: 'Ra',
    numeroAtomique: '88',
    masseAtomique: '226',
    groupe: 'Métaux alcalino-terreux',
    periode: '7',
    configurationElectronique: '[Rn] 7s2',
    pointDeFusion: '700',
    pointDebullition: '1737',
    decouverte: '1898',
    histoire: "Découvert par Marie Curie et Pierre Curie en 1898.",
  ),
  ElementChimique(
    nom: 'Actinium',
    symbole: 'Ac',
    numeroAtomique: '89',
    masseAtomique: '227',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 6d1 7s2',
    pointDeFusion: '1050',
    pointDebullition: '3198',
    decouverte: '1899',
    histoire: "Découvert par Friedrich Oskar Giesel en 1899.",
  ),
  ElementChimique(
    nom: 'Thorium',
    symbole: 'Th',
    numeroAtomique: '90',
    masseAtomique: '232.04',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 6d2 7s2',
    pointDeFusion: '1750',
    pointDebullition: '4788',
    decouverte: '1828',
    histoire: "Découvert par Jöns Jacob Berzelius en 1828.",
  ),
  ElementChimique(
    nom: 'Protactinium',
    symbole: 'Pa',
    numeroAtomique: '91',
    masseAtomique: '231.04',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f2 6d1 7s2',
    pointDeFusion: '1568',
    pointDebullition: '4027',
    decouverte: '1913',
    histoire: "Découvert par Kazimierz Fajans et Oswald Helmuth Göhring en 1913.",
  ),
  ElementChimique(
    nom: 'Uranium',
    symbole: 'U',
    numeroAtomique: '92',
    masseAtomique: '238.03',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f3 6d1 7s2',
    pointDeFusion: '1135',
    pointDebullition: '4131',
    decouverte: '1789',
    histoire: "Découvert par Martin Heinrich Klaproth en 1789.",
  ),
  ElementChimique(
    nom: 'Neptunium',
    symbole: 'Np',
    numeroAtomique: '93',
    masseAtomique: '237',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f4 6d1 7s2',
    pointDeFusion: '644',
    pointDebullition: '3902',
    decouverte: '1940',
    histoire: "Synthétisé par Edwin McMillan et Philip Abelson en 1940.",
  ),
  ElementChimique(
    nom: 'Plutonium',
    symbole: 'Pu',
    numeroAtomique: '94',
    masseAtomique: '244',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f6 7s2',
    pointDeFusion: '640',
    pointDebullition: '3228',
    decouverte: '1940',
    histoire: "Synthétisé par Glenn T. Seaborg, Arthur Wahl, et Joseph W. Kennedy en 1940.",
  ),
  ElementChimique(
    nom: 'Américium',
    symbole: 'Am',
    numeroAtomique: '95',
    masseAtomique: '243',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f7 7s2',
    pointDeFusion: '1176',
    pointDebullition: '2607',
    decouverte: '1944',
    histoire: "Synthétisé par Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, et Albert Ghiorso en 1944.",
  ),
  ElementChimique(
    nom: 'Curium',
    symbole: 'Cm',
    numeroAtomique: '96',
    masseAtomique: '247',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f7 6d1 7s2',
    pointDeFusion: '1340',
    pointDebullition: '3110',
    decouverte: '1944',
    histoire: "Synthétisé par Glenn T. Seaborg, Ralph A. James, et Albert Ghiorso en 1944.",
  ),
  ElementChimique(
    nom: 'Berkélium',
    symbole: 'Bk',
    numeroAtomique: '97',
    masseAtomique: '247',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f9 7s2',
    pointDeFusion: '986',
    pointDebullition: '2627',
    decouverte: '1949',
    histoire: "Synthétisé par Stanley G. Thompson, Albert Ghiorso, et Glenn T. Seaborg en 1949.",
  ),
  ElementChimique(
    nom: 'Californium',
    symbole: 'Cf',
    numeroAtomique: '98',
    masseAtomique: '251',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f10 7s2',
    pointDeFusion: '900',
    pointDebullition: '1472',
    decouverte: '1950',
    histoire: "Synthétisé par Stanley G. Thompson, Albert Ghiorso, et Glenn T. Seaborg en 1950.",
  ),
  ElementChimique(
    nom: 'Einsteinium',
    symbole: 'Es',
    numeroAtomique: '99',
    masseAtomique: '252',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f11 7s2',
    pointDeFusion: '860',
    pointDebullition: '996',
    decouverte: '1952',
    histoire: "Synthétisé par Albert Ghiorso, Stanley G. Thompson, et Glenn T. Seaborg en 1952.",
  ),
  ElementChimique(
    nom: 'Fermium',
    symbole: 'Fm',
    numeroAtomique: '100',
    masseAtomique: '257',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f12 7s2',
    pointDeFusion: '1527',
    pointDebullition: 'Unknown',
    decouverte: '1952',
    histoire: "Synthétisé par Albert Ghiorso, Stanley G. Thompson, et Glenn T. Seaborg en 1952.",
  ),
  ElementChimique(
    nom: 'Mendélévium',
    symbole: 'Md',
    numeroAtomique: '101',
    masseAtomique: '258',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f13 7s2',
    pointDeFusion: '827',
    pointDebullition: 'Unknown',
    decouverte: '1955',
    histoire: "Synthétisé par Albert Ghiorso, Bernard G. Harvey, Gregory R. Choppin, et Glenn T. Seaborg en 1955.",
  ),
  ElementChimique(
    nom: 'Nobélium',
    symbole: 'No',
    numeroAtomique: '102',
    masseAtomique: '259',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1966',
    histoire: "Synthétisé par l'Institut unifié de recherches nucléaires en 1966.",
  ),
  ElementChimique(
    nom: 'Lawrencium',
    symbole: 'Lr',
    numeroAtomique: '103',
    masseAtomique: '262',
    groupe: 'Actinides',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 7s2 7p1',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1961',
    histoire: "Synthétisé par Albert Ghiorso, Torbjørn Sikkeland, Almon E. Larsh, et Robert M. Latimer en 1961.",
  ),

  ElementChimique(
    nom: 'Rutherfordium',
    symbole: 'Rf',
    numeroAtomique: '104',
    masseAtomique: '267',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d2 7s2',
    pointDeFusion: '2100',
    pointDebullition: 'Unknown',
    decouverte: '1964',
    histoire: "Découvert par une équipe à l’Institut unifié de recherches nucléaires à Dubna, Russie, et par Albert Ghiorso à Berkeley, Californie.",
  ),
  ElementChimique(
    nom: 'Dubnium',
    symbole: 'Db',
    numeroAtomique: '105',
    masseAtomique: '270',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d3 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1967',
    histoire: "Découvert par une équipe à Dubna en Russie et par une équipe américaine à Berkeley, Californie.",
  ),
  ElementChimique(
    nom: 'Seaborgium',
    symbole: 'Sg',
    numeroAtomique: '106',
    masseAtomique: '271',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d4 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1974',
    histoire: "Découvert par Albert Ghiorso et une équipe de Berkeley à l’Université de Californie.",
  ),
  ElementChimique(
    nom: 'Bohrium',
    symbole: 'Bh',
    numeroAtomique: '107',
    masseAtomique: '270',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d5 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1981',
    histoire: "Découvert par Peter Armbruster, Gottfried Münzenberg et une équipe au GSI Helmholtz Centre for Heavy Ion Research en Allemagne.",
  ),
  ElementChimique(
    nom: 'Hassium',
    symbole: 'Hs',
    numeroAtomique: '108',
    masseAtomique: '277',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d6 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1984',
    histoire: "Découvert par une équipe à l'Institut GSI en Allemagne, dirigée par Peter Armbruster et Gottfried Münzenberg.",
  ),
  ElementChimique(
    nom: 'Meitnérium',
    symbole: 'Mt',
    numeroAtomique: '109',
    masseAtomique: '278',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d7 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1982',
    histoire: "Découvert au GSI Helmholtz Centre for Heavy Ion Research en Allemagne.",
  ),
  ElementChimique(
    nom: 'Darmstadtium',
    symbole: 'Ds',
    numeroAtomique: '110',
    masseAtomique: '281',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d8 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1994',
    histoire: "Découvert au GSI en Allemagne.",
  ),
  ElementChimique(
    nom: 'Roentgenium',
    symbole: 'Rg',
    numeroAtomique: '111',
    masseAtomique: '282',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d9 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1994',
    histoire: "Découvert au GSI Helmholtz Centre for Heavy Ion Research en Allemagne.",
  ),
  ElementChimique(
    nom: 'Copernicium',
    symbole: 'Cn',
    numeroAtomique: '112',
    masseAtomique: '285',
    groupe: 'Métaux de transition',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d10 7s2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1996',
    histoire: "Découvert au GSI en Allemagne, nommé en l'honneur de Nicolas Copernic.",
  ),
  ElementChimique(
    nom: 'Nihonium',
    symbole: 'Nh',
    numeroAtomique: '113',
    masseAtomique: '286',
    groupe: 'Métaux pauvres',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d10 7s2 7p1',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '2004',
    histoire: "Découvert par le RIKEN au Japon, nommé en l'honneur du Japon (Nihon).",
  ),
  ElementChimique(
    nom: 'Flérovium',
    symbole: 'Fl',
    numeroAtomique: '114',
    masseAtomique: '289',
    groupe: 'Métaux pauvres',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d10 7s2 7p2',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '1998',
    histoire: "Découvert par l’Institut unifié de recherches nucléaires à Dubna, Russie.",
  ),
  ElementChimique(
    nom: 'Moscovium',
    symbole: 'Mc',
    numeroAtomique: '115',
    masseAtomique: '290',
    groupe: 'Métaux pauvres',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d10 7s2 7p3',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '2003',
    histoire: "Découvert à Dubna en Russie et au Lawrence Livermore National Laboratory, nommé en l'honneur de Moscou.",
  ),
  ElementChimique(
    nom: 'Livermorium',
    symbole: 'Lv',
    numeroAtomique: '116',
    masseAtomique: '293',
    groupe: 'Métaux pauvres',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d10 7s2 7p4',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '2000',
    histoire: "Découvert par une collaboration entre Dubna et le Lawrence Livermore National Laboratory.",
  ),
  ElementChimique(
    nom: 'Tennesse',
    symbole: 'Ts',
    numeroAtomique: '117',
    masseAtomique: '294',
    groupe: 'Halogènes',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d10 7s2 7p5',
    pointDeFusion: 'Unknown',
    pointDebullition: 'Unknown',
    decouverte: '2010',
    histoire: "Découvert par une collaboration entre le laboratoire national d’Oak Ridge, l’Institut unifié de recherches nucléaires et le laboratoire national Lawrence Livermore.",
  ),
  ElementChimique(
    nom: 'Oganesson',
    symbole: 'Og',
    numeroAtomique: '118',
    masseAtomique: '294',
    groupe: 'Gaz nobles',
    periode: '7',
    configurationElectronique: '[Rn] 5f14 6d10 7s2 7p6',
    pointDeFusion: 'Unknown',

    pointDebullition: 'Unknown',
    decouverte: '2002',
    histoire: "Découvert par une équipe russe à Dubna en collaboration avec des scientifiques américains au Lawrence Livermore National Laboratory, nommé en l'honneur du physicien russe Yuri Oganessian.",
  ),
];
